name: Check that migrations are up to date

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -y install python3 python3-psycopg2 python3-yaml python3-virtualenv python3-tidylib \
        python3-dateutil python3-markdown python3-pycurl python3-pylibmc python3-tz python3-libsass \
        python3-requests python3-pycryptodome python3-sqlparse python3-qrcode python3-asgiref \
        python3-setproctitle python3-pynliner python3-babel python3-bleach python3-feedparser
        pip install "Django>=4.2,<4.3" cvss
    - name: Install temporary dummy configuration
      run: |
        cat <<EOF > pgweb/settings_local.py
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.dummy',
            }
        }
        EOF
    - name: Check django migrations
      run: |
        python3 ./manage.py makemigrations --check

